name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with: {node-version: 18}
      - run: npm install
      - run: npx tree-sitter generate
      - run: npx tree-sitter test
      - run: npx prebuildify --napi --strip
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}